### ISSUE TITLE
CI/CD testing for this package?

### ISSUE THREAD

**Issue by ssbarnea** [release-depot/toolchest#28]
Are there any plans to enable a CI/CD testing for this package? I am asking this because we needed a pure-python rpm version comparison, which is included in this package.

Still, lack of testing does made me raise this question, as we already got fried by other less maintained dependencies. Thanks.

**Comment by jguiditta** [comment]
Maybe I misunderstand your question, but we have [travis](https://travis-ci.org/release-depot/toolchest) up and running, and you can see the build status on in the [README](https://github.com/release-depot/toolchest#toolchest).  Is there something different you are referring to?  We do not currently include CD with this, though I don't see why we could not consider configuring it if there were a desire to have it.

**Comment by fuzzball81** [comment]
I will also note that tests can be found under the [tests](https://github.com/release-depot/toolchest/tree/master/tests) directory. If I remember correctly the rpm version comparison tools have good coverage.

**Comment by ssbarnea** [comment]
I went to [last merge](https://github.com/release-depot/toolchest/pull/27) commit and looked for some CI responses and I seen nothing. Maybe there is something broken with Travis that makes them disappear after the merge?

BTW, AFAIK, travis migrated everyone from travis.org to travis.com, maybe this has something to do with statuses not being visible. I did not had much interaction with Travis during last year, other than replacing it with github-actions of few projects.

**Comment by ssbarnea** [comment]
I created https://github.com/release-depot/toolchest/pull/29 but the jobs are inside the queue even after 15min, not sure if they will ever run.

Considering that your travis file is very basic, I could easily write you the github-action version for it, if you want.

**Comment by jguiditta** [comment]
Yes, I saw your PR, and I also see that it is just sitting in queued.  I would not be opposed to switching to github-action if that is the better way now.  Patch is absolutely welcome, thanks for offering!

**Comment by jguiditta** [comment]
I should note that I went to travis, disabled and then re-enabled the repo/job, and it does not seem to be fairing any better

**Comment by fuzzball81** [comment]
The jobs are running now and are all failing. https://travis-ci.org/github/release-depot/toolchest

**Comment by jguiditta** [comment]
Now that jobs are running, I don't think we need this issue open anymore.  @ssbarnea if you still have an open question, let me know, otherwise I will close this on monday.
